### ISSUE TITLE
AttributeError: 'long' object has no attribute 'size'

### ISSUE THREAD

**Issue by frederic** [angr/simuvex#12]
When I use the CONCRETIZE option, the following error happens: 
```
Traceback (most recent call last):
  File "./angr-test.py", line 142, in <module>
    dot = analyze_paths(p, p.addr, dot)
  File "./angr-test.py", line 40, in analyze_paths
    parent_p.step()
  File "/home/user/tools/code/angr-dev/angr/angr/path.py", line 432, in step
    self._make_sim_run()
  File "/home/user/tools/code/angr-dev/angr/angr/path.py", line 457, in _make_sim_run
    self._run = self._project.factory.sim_run(self.state, **self._run_args)
  File "/home/user/tools/code/angr-dev/angr/angr/factory.py", line 123, in sim_run
    r = self.sim_block(state, addr=addr, **block_opts)
  File "/home/user/tools/code/angr-dev/angr/angr/factory.py", line 69, in sim_block
    last_stmt=last_stmt)
  File "/home/user/tools/code/angr-dev/simuvex/simuvex/vex/irsb.py", line 62, in __init__
    self._handle_irsb()
  File "/home/user/tools/code/angr-dev/simuvex/simuvex/vex/irsb.py", line 92, in _handle_irsb
    self._handle_statements()
  File "/home/user/tools/code/angr-dev/simuvex/simuvex/vex/irsb.py", line 208, in _handle_statements
    s_stmt = translate_stmt(self.irsb, stmt_idx, self.last_imark, self.state)
  File "/home/user/tools/code/angr-dev/simuvex/simuvex/vex/statements/__init__.py", line 31, in translate_stmt
    s.process()
  File "/home/user/tools/code/angr-dev/simuvex/simuvex/vex/statements/base.py", line 26, in process
    self._execute()
  File "/home/user/tools/code/angr-dev/simuvex/simuvex/vex/statements/wrtmp.py", line 6, in _execute
    data = self._translate_expr(self.stmt.data)
  File "/home/user/tools/code/angr-dev/simuvex/simuvex/vex/statements/base.py", line 36, in _translate_expr
    e = translate_expr(expr, self.imark, self.stmt_idx, self.state)
  File "/home/user/tools/code/angr-dev/simuvex/simuvex/vex/expressions/__init__.py", line 14, in translate_expr
    e.process()
  File "/home/user/tools/code/angr-dev/simuvex/simuvex/vex/expressions/base.py", line 38, in process
    self._execute()
  File "/home/user/tools/code/angr-dev/simuvex/simuvex/vex/expressions/get.py", line 24, in _execute
    self._post_process()
  File "/home/user/tools/code/angr-dev/simuvex/simuvex/vex/expressions/base.py", line 59, in _post_process
    if self.expr.size() != self.size_bits():
AttributeError: 'long' object has no attribute 'size'
```
In https://github.com/angr/simuvex/blob/master/simuvex/vex/expressions/base.py#L94 make_concrete(self), the **expr** member is replaced by a long variable. So all subsequent calls to expr.to_bv() or expr.size() won't work.

Maybe we should create an BVV object : 
self.expr = self.state.se.BVV(concrete_value, self.size_bits())

But I am not sure if we should add contraints (#L92 & #L93) based on BVV object or the original long value.

**Comment by ltfish** [comment]
It's definitely a bug. Can you please print out `self.expr`?

**Comment by frederic** [comment]
I've added two debug prints in https://github.com/angr/simuvex/blob/master/simuvex/vex/expressions/base.py#L94
```
    def _post_process(self):
        if self._post_processed: return
        self._post_processed = True

        if o.SIMPLIFY_EXPRS in self.state.options:
            self.expr = self.state.se.simplify(self.expr)

        self.state.add_constraints(*self._constraints)
        print "_post_process(before make_concrete) self.expr = ", self.expr
        if self.state.se.symbolic(self.expr) and o.CONCRETIZE in self.state.options:
            self.make_concrete()
        print "_post_process(after make_concrete) self.expr = ", self.expr
        if self.expr.size() != self.size_bits():
            raise SimExpressionError("Inconsistent expression size: should be %d but is %d" % (self.size_bits(), self.expr.size()))
```

Output:
```
_post_process(before make_concrete) self.expr =  <BV32 0x7fff0000>
_post_process(after make_concrete) self.expr =  <BV32 0x7fff0000>
_post_process(before make_concrete) self.expr =  <BV32 0x7fff0000>
_post_process(after make_concrete) self.expr =  <BV32 0x7fff0000>
_post_process(before make_concrete) self.expr =  <BV32 0x24>
_post_process(after make_concrete) self.expr =  <BV32 0x24>
_post_process(before make_concrete) self.expr =  <BV32 0x7ffeffdc>
_post_process(after make_concrete) self.expr =  <BV32 0x7ffeffdc>
_post_process(before make_concrete) self.expr =  <BV32 0x7ffeffdc>
_post_process(after make_concrete) self.expr =  <BV32 0x7ffeffdc>
_post_process(before make_concrete) self.expr =  <BV32 0x7fff0000>
_post_process(after make_concrete) self.expr =  <BV32 0x7fff0000>
_post_process(before make_concrete) self.expr =  <BV32 0x4>
_post_process(after make_concrete) self.expr =  <BV32 0x4>
_post_process(before make_concrete) self.expr =  <BV32 0x7ffefffc>
_post_process(after make_concrete) self.expr =  <BV32 0x7ffefffc>
_post_process(before make_concrete) self.expr =  <BV32 BVS('reg_40_0_32', None, None, None, False)>
_post_process(after make_concrete) self.expr =  0
Traceback (most recent call last):
  File "./angr-test.py", line 147, in <module>
    dot = analyze_paths(p, p.addr, dot)
  File "./angr-test.py", line 40, in analyze_paths
    parent_p.step()
  File "/home/user/tools/code/angr-dev/angr/angr/path.py", line 432, in step
    self._make_sim_run()
  File "/home/user/tools/code/angr-dev/angr/angr/path.py", line 457, in _make_sim_run
    self._run = self._project.factory.sim_run(self.state, **self._run_args)
  File "/home/user/tools/code/angr-dev/angr/angr/factory.py", line 123, in sim_run
    r = self.sim_block(state, addr=addr, **block_opts)
  File "/home/user/tools/code/angr-dev/angr/angr/factory.py", line 69, in sim_block
    last_stmt=last_stmt)
  File "/home/user/tools/code/angr-dev/simuvex/simuvex/vex/irsb.py", line 62, in __init__
    self._handle_irsb()
  File "/home/user/tools/code/angr-dev/simuvex/simuvex/vex/irsb.py", line 92, in _handle_irsb
    self._handle_statements()
  File "/home/user/tools/code/angr-dev/simuvex/simuvex/vex/irsb.py", line 208, in _handle_statements
    s_stmt = translate_stmt(self.irsb, stmt_idx, self.last_imark, self.state)
  File "/home/user/tools/code/angr-dev/simuvex/simuvex/vex/statements/__init__.py", line 31, in translate_stmt
    s.process()
  File "/home/user/tools/code/angr-dev/simuvex/simuvex/vex/statements/base.py", line 26, in process
    self._execute()
  File "/home/user/tools/code/angr-dev/simuvex/simuvex/vex/statements/wrtmp.py", line 6, in _execute
    data = self._translate_expr(self.stmt.data)
  File "/home/user/tools/code/angr-dev/simuvex/simuvex/vex/statements/base.py", line 36, in _translate_expr
    e = translate_expr(expr, self.imark, self.stmt_idx, self.state)
  File "/home/user/tools/code/angr-dev/simuvex/simuvex/vex/expressions/__init__.py", line 14, in translate_expr
    e.process()
  File "/home/user/tools/code/angr-dev/simuvex/simuvex/vex/expressions/base.py", line 38, in process
    self._execute()
  File "/home/user/tools/code/angr-dev/simuvex/simuvex/vex/expressions/get.py", line 24, in _execute
    self._post_process()
  File "/home/user/tools/code/angr-dev/simuvex/simuvex/vex/expressions/base.py", line 59, in _post_process
    if self.expr.size() != self.size_bits():
AttributeError: 'long' object has no attribute 'size'
```

**Comment by zardus** [comment]
Hello, do you have a testcase that triggers this?

**Comment by Nixtron** [comment]
Not sure with the latest updates, but with the latest version from pip atleast:
```
import simuvex
import pyvex
import archinfo
s = simuvex.SimState()
s.options.add(simuvex.o.CONCRETIZE)
irsb = pyvex.IRSB("488b06".decode('hex'),0,archinfo.ArchAMD64())
si = simuvex.SimIRSB(s,irsb)
```

**Comment by rhelmot** [comment]
This does, in fact, happen with the latest version! I'll look into it right now.

**Comment by rhelmot** [comment]
...yep, the `CONCRETIZE` option is completely 100% broken and will always make this happen. One sec, I'll push a fix.

**Comment by rhelmot** [comment]
Sorry we took so long on this, the fix was incredibly simple.

> But I am not sure if we should add contraints (#L92 & #L93) based on BVV object or the original long value.

You were absolutely on the right track! The answer to your question is that it doesn't matter, claripy will automatically coerce arguments to the right type if one of them is a python int and the other is a bitvector.
