### ISSUE TITLE
CFGAccurate is broken

### ISSUE THREAD

**Issue by P1kachu** [angr/simuvex#26]
CFGAccurate raises a KeyError due to this [change](https://github.com/angr/simuvex/commit/4f9e438aafafe8cd1effa1ebf8e09ab47c90e175#diff-b59c299c45da5c0dcb058fd22f3e66ceL217) 

Test:
```python2
#!/usr/bin/python2
import angr

#https://github.com/legitbs/quals-2016/tree/master/step
p = angr.Project('step')
main = 0x400fa6
cfg = p.analyses.CFGAccurate(start=main)
```

Execution:
```console
Traceback (most recent call last):
  File "./test.py", line 6, in <module>
    p = angr.Project('step')
  File "/usr/lib/python2.7/site-packages/angr/project.py", line 162, in __init__
    self._simos.configure_project()
  File "/usr/lib/python2.7/site-packages/angr/simos.py", line 193, in configure_project
    super(SimLinux, self).configure_project()
  File "/usr/lib/python2.7/site-packages/angr/simos.py", line 50, in configure_project
    self.proj.loader.perform_irelative_relocs(irelative_resolver)
  File "/usr/lib/python2.7/site-packages/cle-4.6.4.28-py2.7.egg/cle/loader.py", line 799, in perform_irelative_relocs
    val = resolver_func(resolver)
  File "/usr/lib/python2.7/site-packages/angr/simos.py", line 39, in irelative_resolver
    val = resolver()
  File "/usr/lib/python2.7/site-packages/angr/surveyors/caller.py", line 52, in __call__
    return self.result_state.se.simplify(self._cc.get_return_val(self.result_state, stack_base=self.result_state.regs.sp - self._cc.STACKARG_SP_DIFF))
  File "/usr/lib/python2.7/site-packages/simuvex-4.6.5.27-py2.7.egg/simuvex/s_cc.py", line 498, in get_return_val
    if self.is_fp_arg(loc) or self.is_fp_value(val) or isinstance(ty, s_type.SimTypeFloat):
  File "/usr/lib/python2.7/site-packages/simuvex-4.6.5.27-py2.7.egg/simuvex/s_cc.py", line 299, in is_fp_arg
    if arg in self.fp_args or arg == self.FP_RETURN_VAL:
  File "/usr/lib/python2.7/site-packages/simuvex-4.6.5.27-py2.7.egg/simuvex/s_cc.py", line 286, in fp_args
    yield SimRegArg(reg, self.arch.registers[reg][1])
KeyError: 'xmm0'
```

**Comment by rhelmot** [comment]
Cannot reprocud

**Comment by rhelmot** [comment]
I hate ctrl + enter

Cannot reproduce. Please update your version of archinfo.

Also, this has nothing to do with CFGAccurage, the error is raised from during the loading process.

**Comment by P1kachu** [comment]
God I need to sleep. Sorry, my mistake. I had forgotten to update this one
Thanks !
