### ISSUE TITLE
Value error while running patchrex using command line

### ISSUE THREAD

**Issue by ronakdborad** [angr/simuvex#59]
Hi everyone,
While running patchrex, I am getting valueerror. I using command line as follows 

python patch_master.py single /home/ronak/patchrex/myproj/cgc/patcherex-master/test_binaries/CADET_00003 stackretencryption /tmp/CADET_00003_stackretencryption

I am getting below error.
raise ValueError("Trying to store to location without specifying type")
ValueError: Trying to store to location without specifying type

Can anyone please help with it.

Thanks

**Comment by rhelmot** [comment]
Something is out of sync with the rest of the angr projects. Can you post
the full traceback of the error you see?

**Comment by ronakdborad** [comment]
Thanks for your quick response.

Here it is,
(cgc) ronak@ronak-VirtualBox:~/patchrex/myproj/cgc/patcherex-master/patcherex$ ./patch_master.py single /home/ronak/patchrex/myproj/cgc/patcherex-master/test_binaries/CADET_00003 stackretencryption  /tmp/CADET_00003_stackretencryption
<type 'exceptions.OSError'> /home/ronak/patchrex/myproj/cgc/simuvex-master/simuvex/lib/sim_unicorn.so: cannot open shared object file: No such file or directory <traceback object at 0x7f6e9dd59638>
WARNING | 2017-01-11 17:03:33,486 | tracer.Runner | Unable to import shellphish_afl, multicb tracing will be disabled
================================================== process started at 2017-01-11 17:03:33.631657
'./patch_master.py' 'single' '/home/ronak/patchrex/myproj/cgc/patcherex-master/test_binaries/CADET_00003' 'stackretencryption' '/tmp/CADET_00003_stackretencryption'
INFO    | 2017-01-11 17:03:37,777 | patcherex.techniques.StackRetEncryption | Checking reg writes and reads from the graph
Traceback (most recent call last):
  File "./patch_master.py", line 397, in <module>
    res = m(test_bin = False)
  File "./patch_master.py", line 151, in generate_stackretencryption_binary
    patches.extend(StackRetEncryption(self.infile, backend).get_patches())
  File "/home/ronak/patchrex/myproj/cgc/patcherex-master/patcherex/techniques/stackretencryption.py", line 486, in get_patches
    self.safe_functions = self.get_safe_functions()
  File "/home/ronak/patchrex/myproj/cgc/patcherex-master/patcherex/techniques/stackretencryption.py", line 386, in get_safe_functions
    ident = self.patcher.identifier
  File "/home/ronak/patchrex/myproj/cgc/patcherex-master/patcherex/backend.py", line 76, in identifier
    self._identifer = identifier.Identifier(self.project, self.cfg, require_predecessors=False)
  File "/home/ronak/patchrex/myproj/cgc/identifier-master/identifier/identify.py", line 73, in __init__
    self.base_symbolic_state = rop_utils.make_symbolic_state(self.project, self._reg_list)
  File "/home/ronak/patchrex/myproj/cgc/local/lib/python2.7/site-packages/angrop/rop_utils.py", line 180, in make_symbolic_state
    input_state = make_initial_state(project, stack_length)
  File "/home/ronak/patchrex/myproj/cgc/local/lib/python2.7/site-packages/angrop/rop_utils.py", line 168, in make_initial_state
    initial_state.mem[initial_state.regs.sp:] = symbolic_stack
  File "/home/ronak/patchrex/myproj/cgc/simuvex-master/simuvex/plugins/view.py", line 85, in __setitem__
    self.__getitem__(k).store(v)
  File "/home/ronak/patchrex/myproj/cgc/simuvex-master/simuvex/plugins/view.py", line 169, in store
    raise ValueError("Trying to store to location without specifying type")
ValueError: Trying to store to location without specifying type

**Comment by rhelmot** [comment]
Please install the version of [angrop](https://github.com/salls/angrop) from github.
